### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by paul-bayleaf** [cdalitz/abctab2ps#1]
Using valgrind I noticed some memory leaks when using abctab2ps.  E.g.

valgrind ./abctab2ps ../doc/examples/francisque.abc
==22571== Memcheck, a memory error detector
==22571== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==22571== Using Valgrind-3.20.0 and LibVEX; rerun with -h for copyright info
==22571== Command: ./abctab2ps ../doc/examples/francisque.abc
==22571== 
This is abctab2ps, version 1.8.25 (Oct 22 2023)
../doc/examples/francisque.abc: [1] Premier Branle de Poitou - 
Output written on Out.ps (1 page, 1 title, 72113 bytes)
==22571== 
==22571== HEAP SUMMARY:
==22571==     in use at exit: 4,081,073 bytes in 999 blocks
==22571==   total heap usage: 1,110 allocs, 111 frees, 4,189,722 bytes allocated
==22571== 
==22571== LEAK SUMMARY:
==22571==    definitely lost: 360 bytes in 15 blocks
==22571==    indirectly lost: 0 bytes in 0 blocks
==22571==      possibly lost: 0 bytes in 0 blocks
==22571==    still reachable: 4,080,713 bytes in 984 blocks
==22571==         suppressed: 0 bytes in 0 blocks
==22571== Rerun with --leak-check=full to see details of leaked memory
==22571== 
==22571== For lists of detected and suppressed errors, rerun with: -s
==22571== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

For a more complete report
valgrind -s --leak-check=full --show-leak-kinds=all --track-origins=yes ./abctab2ps ../doc/examples/francisque.abc
[valgrind-result.txt](https://github.com/cdalitz/abctab2ps/files/14319718/valgrind-result.txt)

The "still reachable" are not important, these are memory blocks allocated but not freed before exiting.
The "definitely lost" are the memory leaks.

I'll prepare a pull request to fix all of these.

I'm using Linux openSUSE 15.5,  gcc 7.5.0, valgrind-3.20.0

**Comment by cdalitz** [comment]
Dear Paul, thanks for spotting these bugs and for already fixing them. I will have a look at the pull request and merge your changes into the main branch. As the bugs were not critical, I will not make a file release just with these fixes, though.

**Comment by cdalitz** [comment]
Dear Paul, just checked the changes you made, and it seems to me that the delete of *gchords* during the initialization of a new symbol before calling the constructor of *gchords* is wrong, because *gchords* is never initialized to anything before. Calling `delete` might thus result in a crash.

**Comment by paul-bayleaf** [comment]
Dear Christoph, thank you for looking at my pull request.   I think it is ok because gchords is a GchordList* a member of SYMBOL.  All SYMBOL objects are allocated using zrealloc which zeroizes gchords, i.e. a null pointer.    Deleting a null pointer is ok.

**Comment by cdalitz** [comment]
Just merged your changes into the main branch. Thanks for the contribution.
